import React, { useState } from 'react';
import { Calculator, Database, Server, AlertCircle, CheckCircle, Download } from 'lucide-react';

export default function OracleMemorySizingCalculator() {
  const [serverRAM, setServerRAM] = useState(256);
  const [workloadType, setWorkloadType] = useState('oltp');
  const [dbVersion, setDbVersion] = useState('19c');
  const [isMultitenant, setIsMultitenant] = useState(false);
  const [numPDBs, setNumPDBs] = useState(5);
  const [useInMemory, setUseInMemory] = useState(false);
  const [inMemoryPercent, setInMemoryPercent] = useState(25);

  const calculateMemory = () => {
    // Operating System Reserve
    const osReserve = serverRAM * 0.15; // 15% for OS

    // Available for Oracle
    const availableForOracle = serverRAM - osReserve;

    // SGA Calculation based on workload
    let sgaPercent;
    if (workloadType === 'oltp') {
      sgaPercent = 0.60; // 60% for OLTP
    } else if (workloadType === 'dw') {
      sgaPercent = 0.50; // 50% for DW (more PGA needed)
    } else {
      sgaPercent = 0.55; // 55% for Mixed
    }

    let sgaTarget = Math.round(availableForOracle * sgaPercent);

    // In-Memory Column Store
    let inMemorySize = 0;
    if (useInMemory) {
      inMemorySize = Math.round(sgaTarget * (inMemoryPercent / 100));
    }

    // PGA Calculation
    let pgaPercent;
    if (workloadType === 'oltp') {
      pgaPercent = 0.20; // 20% for OLTP
    } else if (workloadType === 'dw') {
      pgaPercent = 0.40; // 40% for DW
    } else {
      pgaPercent = 0.30; // 30% for Mixed
    }

    const pgaTarget = Math.round(availableForOracle * pgaPercent);
    const pgaLimit = Math.round(pgaTarget * 1.5); // PGA_AGGREGATE_LIMIT

    // Multitenant adjustments
    let sgaMinSizePerPDB = 0;
    let pgaLimitPerPDB = 0;
    if (isMultitenant) {
      sgaMinSizePerPDB = Math.round(sgaTarget * 0.05); // 5% min per PDB
      pgaLimitPerPDB = Math.round(pgaLimit / numPDBs);
    }

    // HugePages calculation
    const hugePageSize = 2; // 2MB per page
    const hugePagesNeeded = Math.ceil((sgaTarget * 1024) / hugePageSize);

    return {
      osReserve: Math.round(osReserve),
      availableForOracle: Math.round(availableForOracle),
      sgaTarget,
      inMemorySize,
      effectiveSGA: sgaTarget - inMemorySize,
      pgaTarget,
      pgaLimit,
      sgaMinSizePerPDB,
      pgaLimitPerPDB,
      hugePagesNeeded,
      totalOracleMemory: sgaTarget + pgaTarget
    };
  };

  const results = calculateMemory();

  const generateScript = () => {
    const script = `-- Oracle Memory Configuration Script
-- Generated by Oracle Memory Sizing Calculator
-- Date: ${new Date().toISOString().split('T')[0]}
-- 
-- Server Configuration:
-- Total RAM: ${serverRAM} GB
-- Workload Type: ${workloadType.toUpperCase()}
-- Database Version: Oracle ${dbVersion}
-- Multitenant: ${isMultitenant ? `Yes (${numPDBs} PDBs)` : 'No'}
-- In-Memory Column Store: ${useInMemory ? `Yes (${inMemoryPercent}%)` : 'No'}

-- ============================================
-- RECOMMENDED MEMORY CONFIGURATION (ASMM)
-- ============================================

-- Step 1: Disable AMM (Automatic Memory Management)
ALTER SYSTEM SET MEMORY_TARGET=0 SCOPE=SPFILE;
ALTER SYSTEM SET MEMORY_MAX_TARGET=0 SCOPE=SPFILE;

-- Step 2: Configure ASMM (Automatic Shared Memory Management)
ALTER SYSTEM SET SGA_TARGET=${results.sgaTarget}G SCOPE=SPFILE;
ALTER SYSTEM SET SGA_MAX_SIZE=${results.sgaTarget}G SCOPE=SPFILE;

-- Step 3: Configure PGA
ALTER SYSTEM SET PGA_AGGREGATE_TARGET=${results.pgaTarget}G SCOPE=SPFILE;
${dbVersion !== '11g' ? `ALTER SYSTEM SET PGA_AGGREGATE_LIMIT=${results.pgaLimit}G SCOPE=SPFILE;` : '-- PGA_AGGREGATE_LIMIT not available in 11g'}

${useInMemory ? `-- Step 4: Configure In-Memory Column Store
ALTER SYSTEM SET INMEMORY_SIZE=${results.inMemorySize}G SCOPE=SPFILE;
ALTER SYSTEM SET INMEMORY_QUERY=ENABLE SCOPE=SPFILE;` : ''}

${isMultitenant ? `-- Step 5: Multitenant Resource Management
-- Set minimum SGA per PDB (19c+)
ALTER SYSTEM SET SGA_MIN_SIZE=${results.sgaMinSizePerPDB}G;

-- Configure CDB Resource Plan
BEGIN
  DBMS_RESOURCE_MANAGER.CREATE_PENDING_AREA();
  
  -- Example: Set PGA limit per PDB
  DBMS_RESOURCE_MANAGER.UPDATE_PDB_DIRECTIVE(
    plan => 'DEFAULT_CDB_PLAN',
    pluggable_database => 'YOUR_PDB_NAME',
    shares => 3,
    utilization_limit => 100,
    parallel_server_limit => 100
  );
  
  DBMS_RESOURCE_MANAGER.VALIDATE_PENDING_AREA();
  DBMS_RESOURCE_MANAGER.SUBMIT_PENDING_AREA();
END;
/` : ''}

-- ============================================
-- LINUX HUGEPAGES CONFIGURATION
-- ============================================
-- Run these commands as root on your Linux server:

-- 1. Check current HugePages configuration:
-- grep Huge /proc/meminfo

-- 2. Set HugePages (add to /etc/sysctl.conf):
-- vm.nr_hugepages = ${results.hugePagesNeeded}

-- 3. Apply changes:
-- sysctl -p

-- 4. Verify after DB restart:
-- grep Huge /proc/meminfo
-- HugePages_Free should decrease after Oracle starts

-- ============================================
-- RESTART DATABASE TO APPLY CHANGES
-- ============================================
-- shutdown immediate;
-- startup;

-- ============================================
-- VERIFICATION QUERIES
-- ============================================

-- Check SGA allocation
SELECT name, value/1024/1024/1024 AS gb FROM v$parameter WHERE name LIKE '%sga%';

-- Check PGA configuration
SELECT name, value/1024/1024/1024 AS gb FROM v$parameter WHERE name LIKE '%pga%';

-- Monitor PGA usage
SELECT 
  name, 
  ROUND(value/1024/1024/1024, 2) AS gb 
FROM v$pgastat 
WHERE name IN (
  'aggregate PGA target parameter',
  'total PGA allocated',
  'maximum PGA allocated'
);

-- Check memory advisors
SELECT * FROM v$sga_target_advice ORDER BY sga_size;
SELECT * FROM v$pga_target_advice ORDER BY pga_target_for_estimate;

${useInMemory ? `-- Check In-Memory usage
SELECT * FROM v$inmemory_area;
COL POPULATE_STATUS FORMAT A20
SELECT segment_name, bytes/1024/1024 AS mb, populate_status 
FROM v$im_segments;` : ''}

${isMultitenant ? `-- Monitor PDB resource usage
SELECT con_id, name, shares, utilization_limit 
FROM cdb_rsrc_plan_directives;

SELECT con_id, name, cpu_consumed_time, io_megabytes 
FROM v$rsrcmgrmetric 
ORDER BY cpu_consumed_time DESC;` : ''}
`;
    
    const blob = new Blob([script], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `oracle_memory_config_${serverRAM}GB_${workloadType}.sql`;
    a.click();
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900 p-4 md:p-8">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="flex items-center justify-center gap-3 mb-4">
            <Database className="w-12 h-12 text-blue-400" />
            <h1 className="text-4xl font-bold text-white">Oracle Memory Sizing Calculator</h1>
          </div>
          <p className="text-blue-200 text-lg">Production-Ready ASMM Configuration | 12c → 23ai</p>
          <p className="text-slate-400 text-sm mt-2">By Oracle DBA Performance Architect</p>
        </div>

        <div className="grid md:grid-cols-2 gap-6">
          {/* Input Panel */}
          <div className="bg-slate-800 rounded-xl p-6 border border-slate-700 shadow-2xl">
            <div className="flex items-center gap-2 mb-6">
              <Server className="w-6 h-6 text-blue-400" />
              <h2 className="text-2xl font-bold text-white">Server Configuration</h2>
            </div>

            {/* Server RAM */}
            <div className="mb-6">
              <label className="block text-blue-300 font-semibold mb-2">
                Total Server RAM (GB)
              </label>
              <input
                type="number"
                value={serverRAM}
                onChange={(e) => setServerRAM(Number(e.target.value))}
                className="w-full bg-slate-700 text-white px-4 py-3 rounded-lg border border-slate-600 focus:border-blue-500 focus:outline-none text-lg"
                min="16"
                max="4096"
              />
              <p className="text-slate-400 text-sm mt-2">Typical: 128GB, 256GB, 512GB, 1024GB</p>
            </div>

            {/* Workload Type */}
            <div className="mb-6">
              <label className="block text-blue-300 font-semibold mb-2">Workload Type</label>
              <select
                value={workloadType}
                onChange={(e) => setWorkloadType(e.target.value)}
                className="w-full bg-slate-700 text-white px-4 py-3 rounded-lg border border-slate-600 focus:border-blue-500 focus:outline-none"
              >
                <option value="oltp">OLTP (Transactional)</option>
                <option value="dw">Data Warehouse / Batch</option>
                <option value="mixed">Mixed Workload</option>
              </select>
            </div>

            {/* Database Version */}
            <div className="mb-6">
              <label className="block text-blue-300 font-semibold mb-2">Oracle Version</label>
              <select
                value={dbVersion}
                onChange={(e) => setDbVersion(e.target.value)}
                className="w-full bg-slate-700 text-white px-4 py-3 rounded-lg border border-slate-600 focus:border-blue-500 focus:outline-none"
              >
                <option value="11g">11g</option>
                <option value="12c">12c</option>
                <option value="18c">18c</option>
                <option value="19c">19c (Recommended)</option>
                <option value="21c">21c</option>
                <option value="23ai">23ai</option>
              </select>
            </div>

            {/* Multitenant */}
            <div className="mb-6">
              <label className="flex items-center gap-3 cursor-pointer">
                <input
                  type="checkbox"
                  checked={isMultitenant}
                  onChange={(e) => setIsMultitenant(e.target.checked)}
                  className="w-5 h-5 text-blue-600 bg-slate-700 border-slate-600 rounded focus:ring-blue-500"
                />
                <span className="text-blue-300 font-semibold">Multitenant (CDB/PDB)</span>
              </label>
            </div>

            {isMultitenant && (
              <div className="mb-6 ml-6">
                <label className="block text-blue-300 font-semibold mb-2">Number of PDBs</label>
                <input
                  type="number"
                  value={numPDBs}
                  onChange={(e) => setNumPDBs(Number(e.target.value))}
                  className="w-full bg-slate-700 text-white px-4 py-3 rounded-lg border border-slate-600 focus:border-blue-500 focus:outline-none"
                  min="1"
                  max="100"
                />
              </div>
            )}

            {/* In-Memory Column Store */}
            <div className="mb-6">
              <label className="flex items-center gap-3 cursor-pointer">
                <input
                  type="checkbox"
                  checked={useInMemory}
                  onChange={(e) => setUseInMemory(e.target.checked)}
                  className="w-5 h-5 text-blue-600 bg-slate-700 border-slate-600 rounded focus:ring-blue-500"
                />
                <span className="text-blue-300 font-semibold">Use In-Memory Column Store</span>
              </label>
            </div>

            {useInMemory && (
              <div className="mb-6 ml-6">
                <label className="block text-blue-300 font-semibold mb-2">
                  In-Memory % of SGA
                </label>
                <input
                  type="range"
                  value={inMemoryPercent}
                  onChange={(e) => setInMemoryPercent(Number(e.target.value))}
                  className="w-full"
                  min="10"
                  max="60"
                  step="5"
                />
                <div className="flex justify-between text-slate-400 text-sm mt-1">
                  <span>10%</span>
                  <span className="text-blue-400 font-bold">{inMemoryPercent}%</span>
                  <span>60%</span>
                </div>
              </div>
            )}
          </div>

          {/* Results Panel */}
          <div className="bg-slate-800 rounded-xl p-6 border border-slate-700 shadow-2xl">
            <div className="flex items-center gap-2 mb-6">
              <Calculator className="w-6 h-6 text-green-400" />
              <h2 className="text-2xl font-bold text-white">Recommended Configuration</h2>
            </div>

            {/* Memory Breakdown */}
            <div className="space-y-4 mb-6">
              <div className="bg-slate-900 p-4 rounded-lg border border-slate-600">
                <div className="flex justify-between items-center">
                  <span className="text-slate-300">Total Server RAM</span>
                  <span className="text-white font-bold text-lg">{serverRAM} GB</span>
                </div>
              </div>

              <div className="bg-red-900/20 p-4 rounded-lg border border-red-700/50">
                <div className="flex justify-between items-center">
                  <span className="text-red-300">OS Reserve (15%)</span>
                  <span className="text-red-400 font-bold text-lg">{results.osReserve} GB</span>
                </div>
              </div>

              <div className="bg-blue-900/20 p-4 rounded-lg border border-blue-700/50">
                <div className="flex justify-between items-center">
                  <span className="text-blue-300">Available for Oracle</span>
                  <span className="text-blue-400 font-bold text-lg">{results.availableForOracle} GB</span>
                </div>
              </div>

              <div className="h-px bg-slate-600 my-4"></div>

              <div className="bg-green-900/20 p-4 rounded-lg border border-green-700/50">
                <div className="flex justify-between items-center mb-2">
                  <span className="text-green-300 font-bold">SGA_TARGET</span>
                  <span className="text-green-400 font-bold text-xl">{results.sgaTarget} GB</span>
                </div>
                {useInMemory && (
                  <>
                    <div className="flex justify-between items-center text-sm ml-4 mt-2">
                      <span className="text-slate-400">INMEMORY_SIZE</span>
                      <span className="text-slate-300">{results.inMemorySize} GB</span>
                    </div>
                    <div className="flex justify-between items-center text-sm ml-4">
                      <span className="text-slate-400">Effective Buffer Cache</span>
                      <span className="text-slate-300">{results.effectiveSGA} GB</span>
                    </div>
                  </>
                )}
              </div>

              <div className="bg-purple-900/20 p-4 rounded-lg border border-purple-700/50">
                <div className="flex justify-between items-center mb-2">
                  <span className="text-purple-300 font-bold">PGA_AGGREGATE_TARGET</span>
                  <span className="text-purple-400 font-bold text-xl">{results.pgaTarget} GB</span>
                </div>
                {dbVersion !== '11g' && (
                  <div className="flex justify-between items-center text-sm ml-4">
                    <span className="text-slate-400">PGA_AGGREGATE_LIMIT</span>
                    <span className="text-slate-300">{results.pgaLimit} GB</span>
                  </div>
                )}
              </div>

              {isMultitenant && (
                <div className="bg-yellow-900/20 p-4 rounded-lg border border-yellow-700/50">
                  <div className="text-yellow-300 font-bold mb-2">Multitenant Limits</div>
                  <div className="flex justify-between items-center text-sm">
                    <span className="text-slate-400">SGA_MIN_SIZE per PDB</span>
                    <span className="text-slate-300">{results.sgaMinSizePerPDB} GB</span>
                  </div>
                  <div className="flex justify-between items-center text-sm">
                    <span className="text-slate-400">PGA Limit per PDB</span>
                    <span className="text-slate-300">{results.pgaLimitPerPDB} GB</span>
                  </div>
                </div>
              )}

              <div className="bg-orange-900/20 p-4 rounded-lg border border-orange-700/50">
                <div className="flex justify-between items-center">
                  <span className="text-orange-300 font-bold">HugePages Needed</span>
                  <span className="text-orange-400 font-bold text-lg">{results.hugePagesNeeded.toLocaleString()} pages</span>
                </div>
                <div className="text-slate-400 text-xs mt-2">
                  vm.nr_hugepages = {results.hugePagesNeeded}
                </div>
              </div>
            </div>

            {/* Warnings */}
            <div className="bg-slate-900 p-4 rounded-lg border border-yellow-700/50 mb-6">
              <div className="flex gap-2 mb-2">
                <AlertCircle className="w-5 h-5 text-yellow-400 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="text-yellow-300 font-semibold mb-2">Important Reminders:</p>
                  <ul className="text-slate-300 text-sm space-y-1">
                    <li>• Always test in DEV/UAT before PROD</li>
                    <li>• Monitor V$PGASTAT and V$SGA_TARGET_ADVICE</li>
                    <li>• Configure HugePages BEFORE setting SGA</li>
                    <li>• Database restart required for memory changes</li>
                  </ul>
                </div>
              </div>
            </div>

            {/* Download Button */}
            <button
              onClick={generateScript}
              className="w-full bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white font-bold py-4 px-6 rounded-lg flex items-center justify-center gap-3 transition-all shadow-lg hover:shadow-xl"
            >
              <Download className="w-5 h-5" />
              Download SQL Configuration Script
            </button>

            <p className="text-slate-400 text-xs text-center mt-3">
              Generates complete SQL script with verification queries
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-8 text-center">
          <div className="bg-slate-800 rounded-lg p-6 border border-slate-700">
            <div className="flex items-center justify-center gap-2 mb-3">
              <CheckCircle className="w-5 h-5 text-green-400" />
              <p className="text-slate-300 font-semibold">Based on 15+ Years Production DBA Experience</p>
            </div>
            <p className="text-slate-400 text-sm">
              This calculator follows Oracle best practices for ASMM configuration across 12c, 18c, 19c, 21c, and 23ai.
              Always validate recommendations with AWR/ASH analysis for your specific workload.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}